dataloader:
  batch_size: 64
  sample_size: 256
  shuffle: true
  test_dataset:
    coefficient: 0.01
    params:
      data_root: ./Data/datasets/C-MAPSS/train_FD001.csv
      distribution: geometric
      name: cmapsstproplus1
      neg_one_to_one: true
      period: test
      proportion: 1.0
      save2npy: true
      seed: 123
      style: separate
      window: 96
    sampling_steps: 200
    step_size: 0.05
    target: Utils.Data_utils.cmapss_dataset.CmapssDataset
  train_dataset:
    params:
      data_root: ./Data/datasets/C-MAPSS/train_FD001.csv
      name: cmapsstproplus1
      neg_one_to_one: true
      period: train
      proportion: 1.0
      save2npy: true
      seed: 123
      window: 96
    target: Utils.Data_utils.cmapss_dataset.CmapssDataset
model:
  params:
    attn_pd: 0.0
    beta_schedule: cosine
    d_model: 128
    feature_size: 14
    kernel_size: 1
    loss_type: l2
    maremb_weight: 1.0
    marloss_weight: 1.0
    mlp_hidden_times: 4
    n_heads: 8
    n_layer_dec: 4
    n_layer_enc: 4
    padding_size: 0
    resid_pd: 0.0
    resid_pdrop_markovaware: 1.5
    sampling_timesteps: 500
    seq_length: 96
    timesteps: 500
    use_ff: true
    use_ffloss: true
    use_maremb_weight: false
    use_markovaware: false
    use_markovhead: false
    use_markovloss: false
    use_marloss_weight: false
    use_resid_pdrop_markovaware: false
  target: Models.interpretable_diffusion.gaussian_diffusion.Diffusion_TS
solver:
  base_lr: 1.0e-05
  ema:
    decay: 0.995
    update_interval: 10
  gradient_accumulate_every: 2
  max_epochs: 30000
  results_folder: ./Checkpoints/Checkpoints_cmapsstproplus1
  save_cycle: 100
  scheduler:
    params:
      factor: 0.5
      min_lr: 1.0e-05
      patience: 2000
      threshold: 0.1
      threshold_mode: rel
      verbose: false
      warmup: 500
      warmup_lr: 0.0008
    target: engine.lr_sch.ReduceLROnPlateauWithWarmup
